baseURL = 'https://joestump.github.io/'
languageCode = 'en-us'
title = 'Joe Stump'
theme = 'nostyleplease'

[markup]

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
