baseURL = 'https://joestump.github.io/'
languageCode = 'en-us'
title = 'Joe Stump'
# theme = 'nostyleplease'
theme = 'terminal'

[markup]

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

[params]
  contentTypeName = "hass"
  fullWidthTheme = false
  themeColor = "blue"
#  [params.theme_config]
#    back_home_text = "←"
#    date_format = "Jan 2, 2006"


[languages]
  [languages.en]
    languageName = "English"
    title = "Joe Stump"
    subtitle = "Adventures in Home Automation"
    owner = "Joe Stump"
    keywords = "Home Automation, Home Assistant, ESPHome, ESPresense"
    copyright = "© 2022 Joe Stump"

    [languages.en.params.logo]
      logoText = "Joe Stump"
